language: r
cache: packages

r_packages:
        - Rcpp
        - testthat

notifications:
        email:
                on_success: change
                on_failure: change

addons:
        apt:
                packages:
                        - cmake
