language: r
cache: packages

notifications:
        email:
                on_success: change
                on_failure: change

addons:
        apt:
                packages:
                        - cmake
