sudo: required
services:
        - docker

language: r
cache: packages

r_packages:
        - Rcpp
        - testthat

matrix:
        include:
                - os: linux
                  dist: trusty
                - os: linux
                  dist: xenial
                - os: osx
                  osx_image: xcode8.3
                  latex: false

notifications:
        email:
                on_success: change
                on_failure: change

addons:
        apt:
                packages:
                        - cmake
